export const GET_ALL_PATIENTS_REQUEST = "GET_ALL_PATIENTS_REQUEST";
export const GET_ALL_PATIENTS_FAILURE = "GET_ALL_PATIENTS_FAILURE";
export const GET_ALL_PATIENTS_SUCCESS = "GET_ALL_PATIENTS_SUCCESS";
